var quotes = ["Your perception of me is a reflection of you; my reaction of you is an awareness of me.",
"Set a goal that makes you want to jump out of bed in the morning.",
"Forget your past, forgive yourself, and begin right now.",
"Don't downgrade your dream just to fit your reality. Upgrade your conviction to match your destiny.",
"Its never too late to be what you might've been.",
"Be all in or get half out. There is no in between.",
"It always seems impossible until its done.",
"If you were able to believe in Santa Claus for like 8 years, you can believe in yourself for 5 minutes.",
"Sometimes the wrong choices bring us to the right places.",
"Ships are safe inside the harbor but that is not what ships are for.",
"Do or do not, there is no try.",
"But I am not a tree, and I can move when I want to.",
"We learn by example and by direct experience because there are real limits to the adequacy of verbal instruction.",
"Insight is not a light bulb that goes off inside our heads. It is a flickering candle that can easily be snuffed out.",
"Consistency is the most overrated of all human virtues… I’m someone who changes his mind all the time.",
"Sometimes you need to scorch everything to the ground, and start over. After the burning the soil is richer, and new things can grow. People are like that, too. They start over. They find a way.",
"What made something precious? Losing it and finding it.",
"It is our choices...that show what we truly are, far more than our abilities.",
"Happiness can be found, even in the darkest of times, if one only remembers to turn on the light.",
"Pride is not the opposite of shame, but its source",
"I thought I had lost my honor, and that somehow someone could return it to me. But I know now that no one can give you your honor. It's something you earn for yourself by choosing to do what's right.",
"For me, maturation has been a series of realizing what doesn’t matter.",
"Now when I meet someone with intelligence, beauty, or wealth, I automatically delete those qualities from my perception of their Real Identity. I try to define people by their ambitions, creativity, drive, perspective, attitude, inspirations… that soft gushy core inside the genius billionaire playboy. Love, values, interests, goals.",
"Everything we have is because of someone who rose above their self-absorption. I wouldn’t exist if it weren’t for people who valued adding something to the world above their own comfort.",
"Look at the people around you, and the people on the other side of the earth. Do we leave the earth as if we’d never existed, or do we leave it better?",
"Learning to write teaches me how to read, which teaches me how to think, which teaches me what to ask, what to work on, what to value. How do we navigate this life, with the noble promises of our expanding human knowledge propelling us into the stars, only for the battering of our pathetic human hearts to tear us back down into the grime?",
"I’m not sure when I realized my relative lack of responsibility was an illusion.",
"How do I take responsibility for my species? This is the question I’ve been thinking about. What do you work on when you need to work for your species?",
"What do you think are the biggest challenges and opportunities facing mankind? This question has led to many awesome discussions, so think about it. The only catch is that after you think about it, the follow up question is, “What are you doing to contribute to a solution?” If the answer is, “Nothing,” then we have to ask, “Why are we choosing to work on something we don’t consider important?” So watch out: a question can change everything.",
"That’s the gift that we humans have over the animals. We can choose to be better. If there’s a choice between good and evil, between hope and despair, between progress and complacency, we can choose the light. We can choose life.",
"You don’t know what the future’s going to look like ten, twenty years from now. Embrace ambiguity. I’ll trust that not having the answers to these questions isn’t a limiting factor to my future; that I can simply focus on the now",
"You don’t inherently “deserve” anything, but you damn sure deserve to go out there and try. Keep moving.",
"The busier you are working on you, your life and your happiness, the less time you will have to dwell on another's success other than to celebrate it.",
"If you can create what you fear, you can create what you want.",
"If you do one thing at a time, you can take a break from everything else.",
"A dear friend of mine has a photo of herself as a kid on the wallpaper of her phone. When my friend needs to make a decision, she takes a good hard look at the photo on her phone. Because, it doesn't matter what came after. What matters is this: what is it that she wants for that little girl?",
"You want an obvious life hack? Go to bed.",
"Who you are is defined by what you’re willing to struggle for.",
"You and everyone you know are going to be dead soon. And in the short amount of time between here and there, you have a limited amount of fucks to give. Very few, in fact. And if you go around giving a fuck about everything and everyone without conscious thought or choice—well, then you’re going to get fucked",
"Pain is an inextricable thread in the fabric of life, and to tear it out is not only impossible, but destructive: attempting to tear it out unravels everything else with it. To try to avoid pain is to give too many fucks about pain. In contrast, if you’re able to not give a fuck about the pain, you become unstoppable.",
"The desire for more positive experience is itself a negative experience. And, paradoxically, the acceptance of one’s negative experience is itself a positive experience.",
"And with that, with regards to finding happiness, it seems the best advice is also the simplest: Imagine who you want to be and then step towards it. Dream big and then do something. Anything. The simple act of moving at all will change how you feel about the entire process and serve to inspire you further.",
"Let go of the imagined result—it’s not necessary. The fantasy and the dream are merely tools to get you off your ass. It doesn’t matter if they come true or not. Live, man. Just live. Stop trying to be happy and just be.",
"You will have a growing appreciation for life’s basic experiences. You will learn to measure yourself through a new, healthier means: the pleasures of simple friendship, creating something, helping a person in need, reading a good book, laughing with someone you care about. Sounds boring, doesn’t it? That’s because these things are average. But maybe they’re average for a reason. Because they are what actually matter.",
"If you have to look for what you enjoy in life, then you’re not going to enjoy anything. And the real truth is that you already enjoy something. You already enjoy many things. You’re just choosing to ignore them."];